In [1]:
# Array in NumPy and Tensor in PyTorch

In [2]:
import numpy
#import numpy as num

In [3]:
#creating a 2x2 array
arr=[[1,2],[3,4]]
print(arr)

[[1, 2], [3, 4]]


In [4]:
#convert to NumPy
a=numpy.array(arr)

In [5]:
print(a)

[[1 2]
 [3 4]]


In [6]:
import torch

In [7]:
#convert to PyTorch
b=torch.Tensor(arr)

In [8]:
print(b)

tensor([[1., 2.],
        [3., 4.]])


In [9]:
numpy.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [11]:
#help(numpy.random.rand)
numpy.random.rand(1)

array([0.30430371])

In [12]:
numpy.random.rand(2,2)

array([[0.98308927, 0.34113052],
       [0.72129161, 0.6998972 ]])

In [13]:
torch.rand(2,3)

tensor([[0.5254, 0.2282, 0.3464],
        [0.5892, 0.4932, 0.9698]])

In [14]:
torch.rand(2)

tensor([0.6333, 0.0435])

# Seeds for reproducibility

In [15]:
#NumPy seed
numpy.random.seed(1000)
numpy.random.rand(2,2)

array([[0.65358959, 0.11500694],
       [0.95028286, 0.4821914 ]])

In [16]:
#NumPy seed
numpy.random.seed(1)
numpy.random.rand(2,2)

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01]])

In [17]:
#NumPy seed
numpy.random.seed(1)
numpy.random.rand(2,2)

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01]])

In [18]:
numpy.random.seed(1)
numpy.random.rand(2,2)[0,0]

0.417022004702574

In [19]:
numpy.random.seed(1)
type(numpy.random.rand(2,2)[0,0])

numpy.float64

In [20]:
#no seed
numpy.random.rand(2,2)

array([[0.14675589, 0.09233859],
       [0.18626021, 0.34556073]])

In [21]:
#NumPy seed
numpy.random.seed(1)
numpy.random.rand(2,2)

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01]])

In [22]:
#PyTorch seed
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [23]:
#PyTorch seed
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [24]:
#no seed
torch.rand(2,2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

In [25]:
#PyTorch seed
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [26]:
#PyTorch seed
torch.manual_seed(1)
torch.rand(2,2)

tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]])

In [27]:
#seed for GPU
if torch.cuda.is_available():
    torch.manual_seed_all(0)

# NumPy and PyTorch Bridge

### NumPy to Torch

In [28]:
n=numpy.ones((2,2))

In [29]:
print(type(n))

<class 'numpy.ndarray'>


In [30]:
t=torch.from_numpy(n)

In [31]:
print(t,'\n',type(t))

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64) 
 <class 'torch.Tensor'>


In [32]:
n2=numpy.ones((2,2),dtype=numpy.int8)

In [33]:
t2=torch.from_numpy(n2)

In [34]:
print(type(t2))

<class 'torch.Tensor'>


In [35]:
print(t2)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)


In [36]:
n2=numpy.ones((2,2),dtype=numpy.int16)
t2=torch.from_numpy(n2)
print(type(t2))
print(t2)

<class 'torch.Tensor'>
tensor([[1, 1],
        [1, 1]], dtype=torch.int16)


In [37]:
n2=numpy.ones((2,2),dtype=numpy.int64)
t2=torch.from_numpy(n2)
print(type(t2))
print(t2)

<class 'torch.Tensor'>
tensor([[1, 1],
        [1, 1]])


In [38]:
n2=numpy.ones((2,2),dtype=numpy.float16)
t2=torch.from_numpy(n2)
print(type(t2))
print(t2)

<class 'torch.Tensor'>
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)


### Torch to NumPy

In [39]:
T=torch.ones((2,2))

In [40]:
type(T)

torch.Tensor

In [41]:
TT=T.numpy()

In [42]:
type(TT)

numpy.ndarray

## Resizing Tensors

In [43]:
t=torch.ones((2,2))

In [44]:
print(t.size())
t.view(4)

torch.Size([2, 2])


tensor([1., 1., 1., 1.])

In [45]:
t.view(4).size()

torch.Size([4])

## Tensor Element-wise Addition

In [46]:
a=torch.ones((2,2))
b=torch.ones((2,2))

In [47]:
c=a+b
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [48]:
torch.add(a,b)

tensor([[2., 2.],
        [2., 2.]])

In [49]:
a.add(b)

tensor([[2., 2.],
        [2., 2.]])

In [50]:
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [51]:
#In-place
c.add_(a)

tensor([[3., 3.],
        [3., 3.]])

## Tensor Element-wise Substraction

In [52]:
a=torch.ones(2,2);b=torch.ones(2,2)

In [53]:
print(a,'\n',b)

tensor([[1., 1.],
        [1., 1.]]) 
 tensor([[1., 1.],
        [1., 1.]])


In [54]:
a-b

tensor([[0., 0.],
        [0., 0.]])

In [55]:
#not Inplace
torch.sub(a,b)

tensor([[0., 0.],
        [0., 0.]])

In [56]:
a.sub(b)

tensor([[0., 0.],
        [0., 0.]])

In [57]:
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [58]:
#Inplace
a.sub_(b)

tensor([[0., 0.],
        [0., 0.]])

In [59]:
print(a)

tensor([[0., 0.],
        [0., 0.]])


## Tensor Element-wise Multiplication

In [60]:
a=torch.ones(2,2);b=torch.zeros(2,2)

In [61]:
a*b

tensor([[0., 0.],
        [0., 0.]])

In [62]:
a.mul(b)

tensor([[0., 0.],
        [0., 0.]])

In [63]:
torch.mul(a,b)

tensor([[0., 0.],
        [0., 0.]])

In [64]:
#Inplace
a.mul_(b)

tensor([[0., 0.],
        [0., 0.]])

In [65]:
print(a)

tensor([[0., 0.],
        [0., 0.]])


In [66]:
print(b)

tensor([[0., 0.],
        [0., 0.]])


## Tensor Element-wise Division

In [67]:
a=torch.ones(2,2);b=torch.zeros(2,2)

In [68]:
a/b

tensor([[inf, inf],
        [inf, inf]])

In [69]:
b/a

tensor([[0., 0.],
        [0., 0.]])

In [70]:
torch.div(b,a)

tensor([[0., 0.],
        [0., 0.]])

In [71]:
b.div(a)

tensor([[0., 0.],
        [0., 0.]])

In [72]:
#Inplace
b.div_(a)

tensor([[0., 0.],
        [0., 0.]])

## Torch Mean

In [73]:
a=torch.Tensor([1,2,3,4,5,6,7,8,9,10])

In [74]:
a.size()

torch.Size([10])

In [75]:
a.mean(dim=0)

tensor(5.5000)

In [76]:
#a.mean(dim=1)

In [77]:
b=torch.Tensor([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])

In [78]:
b.mean(dim=1)

tensor([5.5000, 5.5000])

## Tensor standard deviation

In [79]:
a.std(dim=0)

tensor(3.0277)

# PyTorch Fundamentals

## Variables

In [80]:
import torch
from torch.autograd import Variable

In [81]:
a=Variable(torch.ones(2,2),requires_grad=True)

In [82]:
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [83]:
type(a)

torch.Tensor

In [84]:
b=Variable(torch.ones(2,2),requires_grad=True)

In [85]:
print(a+b)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [86]:
print(torch.add(a,b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


## Gradients

In [87]:
x=Variable(torch.ones(2),requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

$$y=5(x+1)^2$$

In [88]:
y=5*(x+1)**2

In [89]:
y

tensor([20., 20.], grad_fn=<MulBackward0>)

In [90]:
o=(1/2)*torch.sum(y)

In [91]:
o

tensor(20., grad_fn=<MulBackward0>)

In [92]:
type(o)

torch.Tensor

In [93]:
o

tensor(20., grad_fn=<MulBackward0>)

In [94]:
o.backward()

In [95]:
o

tensor(20., grad_fn=<MulBackward0>)

In [96]:
x.grad

tensor([10., 10.])

In [97]:
x

tensor([1., 1.], requires_grad=True)

In [98]:
print(x.grad)

tensor([10., 10.])


In [99]:
x=Variable(torch.ones(2),requires_grad=True)
y=5*(x+1)**2
o=(1/2)*torch.sum(y)
o.backward()
x.grad

tensor([10., 10.])